/**
 * 构建脚本：生成 dist/ 目录（纯文件拷贝，无 webpack/rollup 编译）。
 *
 * RK42 提醒：本脚本仅在每次 source 变更后手动执行 `node scripts/build-static.js`
 * 才会更新 dist/。若未重建，dist/ 中可能是旧版本代码（缺少新增的 ES module 函数）。
 * 生产环境 Caddy 若直接 serve dist/，请确保部署前重建：node scripts/build-static.js
 */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');

/**
 * 版本号注入：
 * 读取 package.json 的 version（语义化 MAJOR.MINOR.PATCH）作为唯一真实来源，
 * 生成 dist/version.js，向全局写入 window.APP_VERSION / window.APP_VERSION_LABEL。
 * 所有页面的版本展示均来自此处，改版本只需修改 package.json 一处。
 */
function writeVersionFile() {
  let version = '0.0.0';
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
    if (pkg && pkg.version) version = String(pkg.version);
  } catch (e) {
    console.warn('[build] 无法读取 package.json version，回退为 0.0.0');
  }
  const content =
    '/* AUTO-GENERATED by scripts/build-static.js — 请勿手动修改 */\n' +
    'window.APP_VERSION_BUILD = ' + JSON.stringify(version) + ';\n';
  fs.writeFileSync(path.join(dist, 'version.js'), content, 'utf-8');
  console.log('[build] 注入版本号: Ver-' + version + ' -> dist/version.js (window.APP_VERSION_BUILD)');
}

const filesToCopy = [
  'index.html',
  'login.html',
  'admin-schools.html',
  'super-admin-login.html',
  'help.html',
  'test-report.html',
  'detergent-image-demo.html'
];

const dirsToCopy = [
  'css',
  'js',
  'vendor',
];

// 可选目录：docs/test-results/latest 是运行时由 testReportSync 生成的中间源，
// 全新 clone 部署（仓库未收录该产物）时可能尚不存在，跳过即可，等有测试数据提交后自动生成。
const optionalDirsToCopy = [
  'docs/test-results/latest',
];

function ensureCleanDist() {
  fs.rmSync(dist, { recursive: true, force: true });
  fs.mkdirSync(dist, { recursive: true });
}

function copyFileRelative(relPath) {
  const src = path.join(root, relPath);
  const dst = path.join(dist, relPath);
  if (!fs.existsSync(src)) {
    throw new Error(`Missing required file: ${relPath}`);
  }
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

function copyDirRelative(relPath) {
  const src = path.join(root, relPath);
  const dst = path.join(dist, relPath);
  if (!fs.existsSync(src)) {
    throw new Error(`Missing required directory: ${relPath}`);
  }
  fs.cpSync(src, dst, { recursive: true });
}

// 复制可选目录：源不存在时仅跳过（打印日志），保证全新部署不因缺 docs 中间源而失败。
function copyDirRelativeOptional(relPath) {
  const src = path.join(root, relPath);
  if (!fs.existsSync(src)) {
    console.log(`Skip missing optional directory: ${relPath}`);
    return;
  }
  copyDirRelative(relPath);
}

function main() {
  ensureCleanDist();

  // 注入版本号（必须在拷贝前，确保 dist/version.js 存在）
  writeVersionFile();

  for (const relFile of filesToCopy) {
    copyFileRelative(relFile);
  }

  for (const relDir of dirsToCopy) {
    copyDirRelative(relDir);
  }

  for (const relDir of optionalDirsToCopy) {
    copyDirRelativeOptional(relDir);
  }

  console.log('Build completed: dist/ generated successfully');
}

main();
