/**
 * 构建脚本：生成 dist/ 目录（纯文件拷贝，无 webpack/rollup 编译）。
 *
 * RK42 提醒：本脚本仅在每次 source 变更后手动执行 `node scripts/build-static.js`
 * 才会更新 dist/。若未重建，dist/ 中可能是旧版本代码（缺少新增的 ES module 函数）。
 * 生产环境 Caddy 若直接 serve dist/，请确保部署前重建：node scripts/build-static.js
 */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
// 构建暂存目录：全部拷贝成功后才原子替换 dist/，避免"先删后建"期间线上 404。
const distTmp = path.join(root, 'dist.tmp');
// 替换过程中旧 dist 的临时落点（同分区 rename，微秒级窗口）。
const distOld = path.join(root, 'dist.old');

/**
 * 版本号注入：
 * 读取 package.json 的 version（语义化 MAJOR.MINOR.PATCH）作为唯一真实来源，
 * 生成 dist/version.js，向全局写入 window.APP_VERSION / window.APP_VERSION_LABEL。
 * 所有页面的版本展示均来自此处，改版本只需修改 package.json 一处。
 */
function writeVersionFile(targetRoot) {
  let version = '0.0.0';
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
    if (pkg && pkg.version) version = String(pkg.version);
  } catch (e) {
    console.warn('[build] 无法读取 package.json version，回退为 0.0.0');
  }
  const content =
    '/* AUTO-GENERATED by scripts/build-static.js — 请勿手动修改 */\n' +
    'window.APP_VERSION_BUILD = ' + JSON.stringify(version) + ';\n';
  fs.writeFileSync(path.join(targetRoot, 'version.js'), content, 'utf-8');
  console.log('[build] 注入版本号: Ver-' + version + ' -> version.js (window.APP_VERSION_BUILD)');
}

/**
 * 前端源码根：本仓库把 HTML 入口按职能放在 frontend/pages（正式页面）
 * 与 frontend/demos（实验性 demo），静态资源放在 frontend/{css,js,vendor}。
 *
 * ⚠ 关键约束：**dist/ 内的 URL 布局必须与源码重构前完全一致**。
 * 因为 (1) Caddy 直接 root * /opt/foodsentinel/dist 并依赖 /login.html、/help.html
 * 等根级路径做 rewrite；(2) HTML 内既有 /css/xxx 绝对路径，也有 ./login.html
 * 之类的同级相对路径。故 pages/ 与 demos/ 下的 HTML 一律**扁平化到 dist 根**，
 * 资源目录也保持 dist/{css,js,vendor} 不变。改这里前先确认上述依赖。
 */
const FRONTEND_DIR = 'frontend';
// 会被扁平化到 dist 根的 HTML 源目录（顺序即收集顺序）
const PAGE_DIRS = [path.join(FRONTEND_DIR, 'pages'), path.join(FRONTEND_DIR, 'demos')];
// 资源目录：源 frontend/<name> → 目标 dist/<name>
const ASSET_DIRS = ['css', 'js', 'vendor'];

/**
 * 收集所有 HTML 入口，返回 [{src, dst}]（dst 为 dist 内的根级文件名）。
 * 用目录扫描代替硬编码清单，新增页面无需再改本脚本。
 */
function collectHtmlEntries() {
  const entries = [];
  const seen = new Map();
  for (const dir of PAGE_DIRS) {
    const absDir = path.join(root, dir);
    if (!fs.existsSync(absDir)) {
      throw new Error(`Missing required directory: ${dir}`);
    }
    for (const name of fs.readdirSync(absDir).sort()) {
      if (!name.endsWith('.html')) continue;
      if (seen.has(name)) {
        // 同名会静默覆盖，直接失败更安全
        throw new Error(
          `HTML 入口重名，会导致 dist 内被静默覆盖：${seen.get(name)} 与 ${path.join(dir, name)}`
        );
      }
      seen.set(name, path.join(dir, name));
      entries.push({ src: path.join(dir, name), dst: name });
    }
  }
  if (entries.length === 0) {
    throw new Error('未收集到任何 HTML 入口，请检查 frontend/pages 与 frontend/demos');
  }
  return entries;
}

// TR-Rewrite: 测试报告改为 admin-schools 原生视图（废弃 test-report.html 独立页与 docs/test-results/latest 产物），
// 不再把该目录作为可选拷贝源。

/**
 * 准备暂存目录 dist.tmp/（同时清理上次失败可能残留的 dist.old/）。
 * 注意：此处绝不触碰正在被 Caddy 直供的 dist/。
 */
function prepareStaging() {
  fs.rmSync(distTmp, { recursive: true, force: true });
  fs.rmSync(distOld, { recursive: true, force: true });
  fs.mkdirSync(distTmp, { recursive: true });
}

/**
 * 原子发布：旧的 dist → dist.old，暂存 dist.tmp → dist，成功后清理 dist.old。
 * 两次 rename 同一分区、连续同步执行，线上不可用窗口为微秒级。
 */
function publishStaging() {
  if (fs.existsSync(dist)) {
    fs.renameSync(dist, distOld);
  }
  try {
    fs.renameSync(distTmp, dist);
  } catch (e) {
    // 发布失败：尽量把旧的 dist 放回去，避免线上长时间没有可服务目录
    if (!fs.existsSync(dist) && fs.existsSync(distOld)) {
      fs.renameSync(distOld, dist);
    }
    throw e;
  }
  fs.rmSync(distOld, { recursive: true, force: true });
}

function copyFileRelative(srcRel, targetRoot, dstRel) {
  const src = path.join(root, srcRel);
  const dst = path.join(targetRoot, dstRel || srcRel);
  if (!fs.existsSync(src)) {
    throw new Error(`Missing required file: ${srcRel}`);
  }
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

function copyDirRelative(srcRel, targetRoot, dstRel) {
  const src = path.join(root, srcRel);
  const dst = path.join(targetRoot, dstRel || srcRel);
  if (!fs.existsSync(src)) {
    throw new Error(`Missing required directory: ${srcRel}`);
  }
  fs.cpSync(src, dst, { recursive: true });
}

function main() {
  prepareStaging();

  try {
    // 注入版本号（必须在拷贝前，确保 version.js 存在）
    writeVersionFile(distTmp);

    // HTML 入口：frontend/pages|demos/*.html → dist/*.html（扁平化，保持 URL 不变）
    const htmlEntries = collectHtmlEntries();
    for (const entry of htmlEntries) {
      copyFileRelative(entry.src, distTmp, entry.dst);
    }
    console.log(`[build] HTML 入口 ${htmlEntries.length} 个 -> dist/ 根目录`);

    // 静态资源：frontend/{css,js,vendor} → dist/{css,js,vendor}
    for (const dir of ASSET_DIRS) {
      copyDirRelative(path.join(FRONTEND_DIR, dir), distTmp, dir);
    }
  } catch (e) {
    // 构建失败：清理暂存目录，保持线上 dist/ 原样不动
    fs.rmSync(distTmp, { recursive: true, force: true });
    console.error('[build] 构建失败，已保留原 dist/ 不受影响：', e && e.message);
    process.exit(1);
  }

  publishStaging();
  console.log('Build completed: dist/ generated successfully (atomic replace)');
}

main();
